name: .NET Core

on:
  push:
     branches: 
     - Github-Actions
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name:  dotnet run , git commit and push
      run: |
        cd ConsoleApp1        
        git clone https://dannypc1628:${{ secrets.key }}@github.com/dannypc1628/w3hexschool-Extension-API.git Output
        dotnet run
        cd Output               
        git config --local user.email "${{ secrets.email }}"
        git config --local user.name "dannyLiu"
        git add data.json
        now=$(date +"%F %T")
        git commit -m "在國際標準時間 ${now} 重新上傳" -a
        git push origin master
